# Generated by Django 4.0.2 on 2022-02-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input_form', '0002_businesstype_created_at_businesstype_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputform',
            old_name='contact_number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='inputform',
            name='International_code',
        ),
    ]
